# Netlify configuration file

[build]
  # This command is run to build your site
  command = "npm run build"
  # This is the directory that Netlify will deploy
  publish = "dist"

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200
  force = true # This is equivalent to the '!' in the _redirects file

[[redirects]]
  # The following rule is for single-page applications (SPA)
  # It redirects all other paths to the index.html file
  from = "/*"
  to = "/index.html"
  status = 200
