name = "dynamic-rankers"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "dr-command-center"
database_id = "caed5c77-6a39-4b14-b10d-5437f9a1bea5" # Placeholder ID for local/dev

[vars]
JWT_SECRET = "dr_sovereign_2024"
